=== okazaki13/OpenglTrain/data/spidar_ahs_001.dtd
<!-- SPIDAR API 設定ファイルのDTD -->
<!-- Copyright (c) 2007-2012 Katsuhito AKAHANE. All rights reserved. -->

<!ELEMENT spidar_ahs (
  controller_type,
  spidar_type,
  imp_pset?,imp_qset?,
  mmt_msec,
  sh_spi_usec?,
  sh_spi_mode?,
  voice_navi,
  motor_connection+,
  spidar_motor_definition,
  controller_motor_definition
  ) >

<!ELEMENT controller_type EMPTY>
<!ATTLIST controller_type version (1.0) #REQUIRED >
<!ATTLIST controller_type type    (AHS_009_02_001A)    #REQUIRED >
<!ATTLIST controller_type author  (Katsuhito_AKAHANE)  #REQUIRED >

<!ELEMENT spidar_type EMPTY>
<!ATTLIST spidar_type name (SPIDAR-4|SPIDAR-G|SH_SPIDAR-G|SPIDAR-X|SPIDAR-8|special) #REQUIRED >
<!ATTLIST spidar_type pos_unit        (m)       #REQUIRED >
<!ATTLIST spidar_type pos_vel_unit    (mPers)   #REQUIRED >
<!ATTLIST spidar_type ori_unit        (rad)     #IMPLIED  >
<!ATTLIST spidar_type ori_vel_unit    (radPers) #IMPLIED  >
<!ATTLIST spidar_type force_unit      (N)       #REQUIRED >
<!ATTLIST spidar_type torque_unit     (Nm)      #IMPLIED  >

<!ELEMENT vr_vs_device_scale EMPTY>
<!ATTLIST vr_vs_device_scale pos_x    CDATA #REQUIRED >
<!ATTLIST vr_vs_device_scale pos_y    CDATA #REQUIRED >
<!ATTLIST vr_vs_device_scale pos_z    CDATA #REQUIRED >
<!ATTLIST vr_vs_device_scale ori_phi  CDATA #REQUIRED >
<!ATTLIST vr_vs_device_scale force_x  CDATA #REQUIRED >
<!ATTLIST vr_vs_device_scale force_y  CDATA #REQUIRED >
<!ATTLIST vr_vs_device_scale force_z  CDATA #REQUIRED >
<!ATTLIST vr_vs_device_scale torque_x CDATA #REQUIRED >
<!ATTLIST vr_vs_device_scale torque_y CDATA #REQUIRED >
<!ATTLIST vr_vs_device_scale torque_z CDATA #REQUIRED >

<!ELEMENT imp_pset EMPTY>
<!ATTLIST imp_pset repeat    CDATA #IMPLIED >
<!ATTLIST imp_pset sigma     CDATA #IMPLIED >
<!ATTLIST imp_pset posxN     CDATA #IMPLIED >
<!ATTLIST imp_pset orixN     CDATA #IMPLIED >

<!ELEMENT imp_qset EMPTY>
<!ATTLIST imp_qset repeat    CDATA #IMPLIED >
<!ATTLIST imp_qset sigma     CDATA #IMPLIED >
<!ATTLIST imp_qset lambda_f  CDATA #IMPLIED >
<!ATTLIST imp_qset lambda_t  CDATA #IMPLIED >

<!ELEMENT control_type EMPTY>
<!ATTLIST control_type id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST control_type name (impedance|admittance|hybrid|open_impedance|special) #REQUIRED >

<!ELEMENT mmt_msec EMPTY>
<!ATTLIST mmt_msec unit (msec|sec|kHz|Hz) #REQUIRED >
<!ATTLIST mmt_msec val CDATA #REQUIRED >

<!ELEMENT sh_spi_usec EMPTY>
<!ATTLIST sh_spi_usec unit (usec|msec|sec|kHz|Hz) #REQUIRED >
<!ATTLIST sh_spi_usec val CDATA #REQUIRED >

<!ELEMENT sh_spi_mode EMPTY>
<!ATTLIST sh_spi_mode mode (normal|vc|w3p4|demo) #REQUIRED >


<!ELEMENT voice_navi EMPTY>
<!--<!ATTLIST voice_navi mute (false|true) #REQUIRED >-->
<!ATTLIST voice_navi skill (beginner|specialist) #REQUIRED >


<!ELEMENT motor_connection EMPTY >
<!ATTLIST motor_connection spidar_ch_id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST motor_connection controller_ch_id (-1|0|1|2|3|4|5|6|7) #REQUIRED >


<!--<!ELEMENT SPIDARの種類の定義 ()>-->
<!ELEMENT spidar_motor_definition (
  control_type+,
  param*,
  motor_pos+,  
  grip_pos+,
  motor_force+,
  motor_pwm+,
  motor_pid_imp*,
  motor_pid_adm*,
  correction_targetForceOpen*,
  correction_adc_to_force*
  )>

<!ELEMENT param EMPTY>
<!ATTLIST param name  CDATA #REQUIRED >
<!ATTLIST param value CDATA #REQUIRED >

<!ELEMENT motor_pos EMPTY >
<!ATTLIST motor_pos id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST motor_pos unit (mm) #REQUIRED >
<!ATTLIST motor_pos x CDATA #REQUIRED >
<!ATTLIST motor_pos y CDATA #REQUIRED >
<!ATTLIST motor_pos z CDATA #REQUIRED >

<!ELEMENT grip_pos EMPTY >
<!ATTLIST grip_pos id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST grip_pos unit (mm) #REQUIRED >
<!ATTLIST grip_pos x CDATA #REQUIRED >
<!ATTLIST grip_pos y CDATA #REQUIRED >
<!ATTLIST grip_pos z CDATA #REQUIRED >

<!ELEMENT motor_force EMPTY >
<!ATTLIST motor_force id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST motor_force unit (N) #REQUIRED >
<!ATTLIST motor_force min CDATA #REQUIRED >
<!ATTLIST motor_force max CDATA #REQUIRED >

<!ELEMENT motor_pwm EMPTY >
<!ATTLIST motor_pwm id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST motor_pwm unit (percent) #REQUIRED >
<!ATTLIST motor_pwm calibDuty         CDATA #REQUIRED >
<!ATTLIST motor_pwm afterCalibDuty    CDATA #REQUIRED >
<!ATTLIST motor_pwm maxDuty           CDATA #REQUIRED >

<!ELEMENT motor_pid_imp EMPTY >
<!ATTLIST motor_pid_imp id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST motor_pid_imp unit (relative) #REQUIRED >
<!ATTLIST motor_pid_imp Kp CDATA #REQUIRED >
<!ATTLIST motor_pid_imp Ki CDATA #REQUIRED >
<!ATTLIST motor_pid_imp Kd CDATA #REQUIRED >
<!ATTLIST motor_pid_imp Kb CDATA #IMPLIED >
<!ATTLIST motor_pid_imp Km CDATA #IMPLIED >

<!ELEMENT motor_pid_adm EMPTY >
<!ATTLIST motor_pid_adm id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST motor_pid_adm unit (relative) #REQUIRED >
<!ATTLIST motor_pid_adm Kp CDATA #REQUIRED >
<!ATTLIST motor_pid_adm Ki CDATA #REQUIRED >
<!ATTLIST motor_pid_adm Kd CDATA #REQUIRED >
<!ATTLIST motor_pid_adm add_count CDATA #REQUIRED >

<!ELEMENT correction_targetForceOpen EMPTY >
<!ATTLIST correction_targetForceOpen id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST correction_targetForceOpen unit (relative) #REQUIRED >
<!ATTLIST correction_targetForceOpen isActive (true|false) #REQUIRED >
<!ATTLIST correction_targetForceOpen a0 CDATA #REQUIRED >
<!ATTLIST correction_targetForceOpen a1 CDATA #REQUIRED >
<!ATTLIST correction_targetForceOpen a2 CDATA #REQUIRED >
<!ATTLIST correction_targetForceOpen a3 CDATA #REQUIRED >

<!ELEMENT correction_adc_to_force EMPTY >
<!ATTLIST correction_adc_to_force id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST correction_adc_to_force unit (relative) #REQUIRED >
<!ATTLIST correction_adc_to_force isActive (true|false) #REQUIRED >
<!ATTLIST correction_adc_to_force a0 CDATA #REQUIRED >
<!ATTLIST correction_adc_to_force a1 CDATA #REQUIRED >
<!ATTLIST correction_adc_to_force a2 CDATA #REQUIRED >
<!ATTLIST correction_adc_to_force a3 CDATA #REQUIRED >




<!ELEMENT controller_motor_definition (
  rotation_dir+,
  pully+,
  encoder+,
  dc_motor+
  )>

<!ELEMENT rotation_dir EMPTY >
<!ATTLIST rotation_dir id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST rotation_dir unit (direction) #REQUIRED >
<!ATTLIST rotation_dir direction (a|b|A|B) #REQUIRED >

<!ELEMENT pully EMPTY >
<!ATTLIST pully id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST pully unit (mm) #REQUIRED >
<!ATTLIST pully radius CDATA #REQUIRED >

<!ELEMENT encoder EMPTY >
<!ATTLIST encoder id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST encoder unit (pulsePerTurn) #REQUIRED >
<!ATTLIST encoder resolution CDATA #REQUIRED >
<!ATTLIST encoder interpolation (true|false) #REQUIRED >

<!ELEMENT dc_motor EMPTY >
<!ATTLIST dc_motor id (-1|0|1|2|3|4|5|6|7) #REQUIRED >
<!ATTLIST dc_motor unit (mNmPerA) #REQUIRED >
<!ATTLIST dc_motor torque_constant CDATA #REQUIRED >
<!ATTLIST dc_motor unit_r (ohm) #REQUIRED >
<!ATTLIST dc_motor terminal_r CDATA #REQUIRED >
<!ATTLIST dc_motor unit_v (v) #REQUIRED >
<!ATTLIST dc_motor terminal_v CDATA #REQUIRED >

=== okazaki13/OpenglTrain/data/spidar_isotropic_koyama001.xml
<?xml version="1.0" encoding="shift_jis"?>
<!DOCTYPE spidar_ahs SYSTEM "spidar_ahs_001.dtd" >
<!-- SPIDAR/AHS System Information File                              -->
<!-- Copyright (c) 2007-2009 Katsuhito AKAHANE. All rights reserved. -->

<!-- for New SPIDAR-ISO designed by Tatsuya KOYAMA (2011/12)-->


<spidar_ahs>
  <controller_type version="1.0" type="AHS_009_02_001A" author="Katsuhito_AKAHANE"/>
  <!-- SPIDARのタイプの設定-->
  <spidar_type name="SPIDAR-G" pos_unit="m" pos_vel_unit="mPers" ori_unit="rad" ori_vel_unit="radPers" force_unit="N" torque_unit="Nm"/>
  <imp_pset repeat="2" sigma="0.001" posxN="0.9" orixN="60.0"/>
  <imp_qset repeat="8" sigma="0.05" lambda_f="1.0" lambda_t="1.0"/>
  <!--<imp_qset repeat="8" sigma="0.05" lambda_f="1.0" lambda_t="0.001"/>-->

  <!--マルチメディアタイマの設定-->
  <mmt_msec unit="kHz" val="1.0"/>
  <!--音声案内の設定-->
  <voice_navi skill="beginner"/>


  <!-- SPIDAR系モータ番号とコントローラ系モータ番号の関連づけ -->
  <!-- SPIDAR-G or そのままの接続でOKなSPIDAR -->
  <motor_connection spidar_ch_id="-1" controller_ch_id="-1"/>
  <!-- ↑の記述は↓の8行と同じ事 idがマイナスのときはすべてのidが同じ値に設定される-->
  <!--
  <motor_connection spidar_ch_id="0" controller_ch_id="0"/>
  <motor_connection spidar_ch_id="1" controller_ch_id="1"/>
  <motor_connection spidar_ch_id="2" controller_ch_id="2"/>
  <motor_connection spidar_ch_id="3" controller_ch_id="3"/>
  <motor_connection spidar_ch_id="4" controller_ch_id="4"/>
  <motor_connection spidar_ch_id="5" controller_ch_id="5"/>
  <motor_connection spidar_ch_id="6" controller_ch_id="6"/>
  <motor_connection spidar_ch_id="7" controller_ch_id="7"/>
  -->
  
  <!-- SPIDAR-4 (2組分) -->
  <!--
  <motor_connection spidar_ch_id="0" controller_ch_id="6"/>
  <motor_connection spidar_ch_id="1" controller_ch_id="4"/>
  <motor_connection spidar_ch_id="2" controller_ch_id="3"/>
  <motor_connection spidar_ch_id="3" controller_ch_id="1"/>
  <motor_connection spidar_ch_id="4" controller_ch_id="5"/>
  <motor_connection spidar_ch_id="5" controller_ch_id="7"/>
  <motor_connection spidar_ch_id="6" controller_ch_id="0"/>
  <motor_connection spidar_ch_id="7" controller_ch_id="2"/>
  -->
  

  <!-- SPIDARの情報定義（idはSPIDAR系モータ番号） -->
  <spidar_motor_definition>
    <!-- 制御タイプの設定-->
    <control_type id="-1"  name="open_impedance"/>

    <!--xml中のパラメータは32個までOK-->
    <!--
    <param name="dx" value="18.75"/>
    <param name="dy" value="26.5165"/>
    <param name="dz" value="18.75"/>
    <param name="r"  value="26.5165"/>
    -->
    <param name="gxz" value="25.62178"/>
    <param name="gy" value="23.8438"/>
    <param name="mxz" value="15.23972"/>
    <param name="my"  value="35.0"/>

    <!--糸の接続点（モータからの糸の出口）-->
    <!--motor_posのx,y,zの値の指定には数式の +,-,/,*,cos(),sin(),tan()　に対応予定 -->
    <!--pi=3.141592...は PI or pi or Pi or 4.0*atan(1.0) で計算可能-->
    
    <!--SPIDAR-ISO用鉛直方向がz方向-->
    <motor_pos   id="0" unit="mm" x=" mxz"  y=" -my" z=" -mxz" />
    <motor_pos   id="1" unit="mm" x=" mxz"  y=" my"  z=" -mxz" />
    <motor_pos   id="2" unit="mm" x=" mxz"  y=" my"  z=" mxz" />
    <motor_pos   id="3" unit="mm" x=" mxz"  y=" -my" z=" mxz" />
    <motor_pos   id="4" unit="mm" x=" -mxz" y=" -my" z=" mxz" />
    <motor_pos   id="5" unit="mm" x=" -mxz" y=" my"  z=" mxz" />
    <motor_pos   id="6" unit="mm" x=" -mxz" y=" my"  z=" -mxz" />
    <motor_pos   id="7" unit="mm" x=" -mxz" y=" -my" z=" -mxz" />

    <!--糸の接続点（グリップ上）-->
    <!--grip_posのx,y,zの値の指定には数式の +,-,/,*,cos(),sin(),tan()　に対応予定 -->
    <grip_pos    id="0" unit="mm" x=" gxz"  y=" -gy" z=" 0.0"/>
    <grip_pos    id="1" unit="mm" x=" 0.0"  y=" gy"  z=" -gxz"/>
    <grip_pos    id="2" unit="mm" x=" 0.0"  y=" gy"  z=" gxz"/>
    <grip_pos    id="3" unit="mm" x=" gxz"  y=" -gy" z=" 0.0"/>
    <grip_pos    id="4" unit="mm" x=" -gxz" y=" -gy" z=" 0.0"/>
    <grip_pos    id="5" unit="mm" x=" 0.0"  y=" gy"  z=" gxz"/>
    <grip_pos    id="6" unit="mm" x=" 0.0"  y=" gy"  z=" -gxz"/>
    <grip_pos    id="7" unit="mm" x=" -gxz" y=" -gy" z=" 0.0"/>

    <!-- 最大張力・最低張力の設定 max を5.0から1.2に変更 -->
    <motor_force id="-1" unit="N"  min="0.0018" max="1.2"/>

    <!-- キャリブレーション時のPWMのデューティ比の設定 -->
    <motor_pwm   id="-1" unit="percent" calibDuty="20.0" afterCalibDuty="10.0" maxDuty="100.0"/>

    <!-- motor_pid_imp　リリース時は削除 -->
    <!-- インピーダンス制御時のPIDの係数設定 -->
    <!--<motor_pid_imp   id="-1" unit="relative" Kp="1.25" Ki="0.125" Kd="-0.25"/>-->
    <motor_pid_imp   id="-1" unit="relative" Kp="0.75" Ki="0.005" Kd="-0.25"/>

    <!-- motor_pid_adm　リリース時は削除 -->
    <!-- アドミッタンス制御時のPIDの係数設定 -->
    <motor_pid_adm   id="-1" unit="relative" Kp="-32.0" Ki="-0.01" Kd="0.01" add_count="-20"/>

    <!--
    <motor_pid_adm   id="0" unit="relative" Kp="-128.0" Ki="-0.1" Kd="0.0" add_count="10"/>
    <motor_pid_adm   id="1" unit="relative" Kp="-128.0" Ki="-0.1" Kd="0.0" add_count="10"/>
    <motor_pid_adm   id="2" unit="relative" Kp="-128.0" Ki="-0.1" Kd="0.0" add_count="10"/>
    <motor_pid_adm   id="3" unit="relative" Kp="-128.0" Ki="-0.1" Kd="0.0" add_count="10"/>
    <motor_pid_adm   id="4" unit="relative" Kp="-128.0" Ki="-0.1" Kd="0.0" add_count="10"/>
    <motor_pid_adm   id="5" unit="relative" Kp="-128.0" Ki="-0.1" Kd="0.0" add_count="10"/>
    <motor_pid_adm   id="6" unit="relative" Kp="-128.0" Ki="-0.1" Kd="0.0" add_count="10"/>
    <motor_pid_adm   id="7" unit="relative" Kp="-128.0" Ki="-0.1" Kd="0.0" add_count="10"/>
    -->

    <correction_targetForceOpen id="-1" isActive="true" unit="relative" a0="-1.22740366847795e-4" a1="2.93930031745995e-2" a2="-1.27702281776925e-1" a3="0"/>
    <correction_adc_to_force id="-1" isActive="true" unit="relative" a0="5.69968601828734e-5" a1="3.46453656738059e-3" a2="-2.49144486294754.e-2" a3="0"/>

  </spidar_motor_definition>

  <!-- コントローラに接続されているモータの定義（idはコントローラ系モータ番号） -->
  <controller_motor_definition>
    <rotation_dir id="0" unit="direction" direction="b"/>
    <rotation_dir id="1" unit="direction" direction="b"/>
    <rotation_dir id="2" unit="direction" direction="a"/>
    <rotation_dir id="3" unit="direction" direction="a"/>
    <rotation_dir id="4" unit="direction" direction="b"/>
    <rotation_dir id="5" unit="direction" direction="b"/>
    <rotation_dir id="6" unit="direction" direction="a"/>
    <rotation_dir id="7" unit="direction" direction="a"/>

    <!--プーリの半径 [mm]-->
    <pully    id="-1" unit="mm" radius="5.1/2.0"/>

    <!--Maxon 271107(201940:MRエンコーダTypeM 512Imp) の相順(a or b)と分解能[パルス/回転]-->
    <encoder  id="-1" unit="pulsePerTurn" resolution="512" interpolation="false"/>

    <!--Maxon 271107(220429:RE-max24) のトルク定数 [mNm/A] と端子間抵抗 [ohm] と実際にモータにかけている端子間電圧[v]-->
    <!--<dc_motor id="-1" unit="mNmPerA" torque_constant="21.3" unit_r="ohm" terminal_r="6.46*0.5" unit_v="v" terminal_v="12.0"/>-->
    <!--<dc_motor id="-1" unit="mNmPerA" torque_constant="17.2951" unit_r="ohm" terminal_r="6.46*0.8" unit_v="v" terminal_v="12.0"/>-->
    <!--<dc_motor id="-1" unit="mNmPerA" torque_constant="21.3*0.8" unit_r="ohm" terminal_r="6.46*0.8" unit_v="v" terminal_v="12.0"/>-->
    
    <!--Maxon 216010のトルク定数 [mNm/A] と端子間抵抗 [ohm] と実際にモータにかけている端子間電圧[v]-->
    <dc_motor id="-1" unit="mNmPerA" torque_constant="10.1" unit_r="ohm" terminal_r="8.30*0.8" unit_v="v" terminal_v="12.0"/>

  </controller_motor_definition>



</spidar_ahs>

=== okazaki13/OpenglTrain/data/spidar_8_003.xml
<?xml version="1.0" encoding="shift_jis"?>
<!DOCTYPE spidar_ahs SYSTEM "spidar_ahs_001.dtd" >
<!-- SPIDAR/AHS System Information File                              -->
<!-- Copyright (c) 2007-2009 Katsuhito AKAHANE. All rights reserved. -->

<spidar_ahs>
  <controller_type version="1.0" type="AHS_009_02_001A" author="Katsuhito_AKAHANE"/>
  <!-- SPIDARのタイプの設定-->
  <spidar_type name="SPIDAR-8" pos_unit="mm" pos_vel_unit="mPers" ori_unit="rad" ori_vel_unit="radPers" force_unit="N" torque_unit="mNm"/>
  <imp_pset repeat="2" sigma="0.001" posxN="1.0" orixN="60.0"/>
  <imp_qset repeat="8" sigma="0.025" lambda_f="1.0" lambda_t="0.001"/>

  <!--マルチメディアタイマの設定-->
  <mmt_msec unit="kHz" val="1.0"/>
  <!--SH拡張時 SPIのタイマの設定-->
  <sh_spi_usec unit="kHz" val="10.0"/>
  <!--音声案内の設定-->
  <voice_navi skill="beginner"/>

  <!-- SPIDAR系モータ番号とコントローラ系モータ番号の関連づけ -->
  <!-- SPIDAR-G or そのままの接続でOKなSPIDAR -->
  <motor_connection spidar_ch_id="-1" controller_ch_id="-1"/>
  <!-- ↑の記述は↓の8行と同じ事 idがマイナスのときはすべてのidが同じ値に設定される-->
  <!--
  <motor_connection spidar_ch_id="0" controller_ch_id="0"/>
  <motor_connection spidar_ch_id="1" controller_ch_id="1"/>
  <motor_connection spidar_ch_id="2" controller_ch_id="2"/>
  <motor_connection spidar_ch_id="3" controller_ch_id="3"/>
  <motor_connection spidar_ch_id="4" controller_ch_id="4"/>
  <motor_connection spidar_ch_id="5" controller_ch_id="5"/>
  <motor_connection spidar_ch_id="6" controller_ch_id="6"/>
  <motor_connection spidar_ch_id="7" controller_ch_id="7"/>
  -->

  <!-- SPIDARの情報定義（idはSPIDAR系モータ番号） -->
  <spidar_motor_definition>
    <!-- 制御タイプの設定-->
    <!-- 1つのコントローラでSPIDARが複数構築できる場合 -->
    <!--（例えば SPIDAR-Gは1組だがSPIDAR4は2組構築可能）-->
    <!-- idに指定すればそのSPIDARの制御タイプを変更できる-->
    <!--<control_type id="-1" name="hybrid"/>-->
    <control_type id="-1"  name="open_impedance"/>

    <!--xml中のパラメータは128個までOK-->
    <param name="dx" value="360.0/2.0"/>
    <param name="dy" value="260.0/2.0"/>
    <param name="dz" value="260.0/2.0"/>
    <param name="Motor_r" value="24.0/2.0"/>
    <param name="d_frame2exit" value="15.0/2.0"/>
    <param name="d_frame2exit2" value="20.0/2.0"/>
    <param name="calib_x" value="0.0"/>
    <param name="calib_y" value="-dy+10.0"/>
    <param name="calib_z" value="-dz+30.0"/>
    
    <param name="calib_r" value="40.0/2.0"/>
    <param name="calib_dx" value="10.0"/>

    <!--糸の接続点（モータからの糸の出口）-->
    <!--motor_posのx,y,zの値の指定には数式の +,-,/,*,cos(),sin(),tan()　に対応予定 -->
    <!--pi=3.141592...は PI or pi or Pi or 4.0*atan(1.0) で計算可能-->
    <motor_pos   id="0" unit="mm" x="dx-d_frame2exit2"    y="-dy+d_frame2exit"  z="-dz+Motor_r*5" />
    <motor_pos   id="1" unit="mm" x="dx-Motor_r*5"  y="dy-d_frame2exit"   z="-dz+d_frame2exit2"   />
    
    <motor_pos   id="2" unit="mm" x="dx-d_frame2exit2"    y="dy-d_frame2exit"   z="dz-Motor_r*5"  />
    <motor_pos   id="3" unit="mm" x="dx-d_frame2exit2"    y="-dy+d_frame2exit"  z="-dz+Motor_r*7" />
    <motor_pos   id="4" unit="mm" x="dx-Motor_r*3"  y="dy-d_frame2exit"   z="-dz+d_frame2exit2"   />

    <motor_pos   id="5" unit="mm" x="Motor_r*2.0"       y="dy-d_frame2exit"   z="dz-d_frame2exit2"    />
    <motor_pos   id="6" unit="mm" x="Motor_r*2.0"       y="-dy+d_frame2exit"  z="dz-d_frame2exit2"    />
    <motor_pos   id="7" unit="mm" x="dx-d_frame2exit2"    y=" dy-d_frame2exit"  z="dz-Motor_r*3"  />

    <!--糸の接続点（グリップ上）-->
    <!--grip_posのx,y,zの値の指定には数式の +,-,/,*,cos(),sin(),tan()　に対応予定 -->
    <grip_pos    id="0" unit="mm" x="calib_x+calib_dx" y="calib_y+calib_r*sin(pi/6.0)" z="calib_z-calib_r*cos(pi/6.0)" />
    <grip_pos    id="1" unit="mm" x="calib_x+calib_dx" y="calib_y+calib_r*sin(pi/6.0)" z="calib_z-calib_r*cos(pi/6.0)" />

    <grip_pos    id="2" unit="mm" x="calib_x+calib_dx" y="calib_y+calib_r*sin(pi/2.0)" z="calib_z+calib_r*cos(pi/2.0)" />
    <grip_pos    id="3" unit="mm" x="calib_x+calib_dx" y="calib_y+calib_r*sin(pi/2.0)" z="calib_z+calib_r*cos(pi/2.0)" />
    <grip_pos    id="4" unit="mm" x="calib_x+calib_dx" y="calib_y+calib_r*sin(pi/2.0)" z="calib_z+calib_r*cos(pi/2.0)" />

    <grip_pos    id="5" unit="mm" x="calib_x+calib_dx" y="calib_y+calib_r*sin(pi/6.0)" z="calib_z+calib_r*cos(pi/6.0)" />
    <grip_pos    id="6" unit="mm" x="calib_x+calib_dx" y="calib_y+calib_r*sin(pi/6.0)" z="calib_z+calib_r*cos(pi/6.0)" />
    <grip_pos    id="7" unit="mm" x="calib_x+calib_dx" y="calib_y+calib_r*sin(pi/6.0)" z="calib_z+calib_r*cos(pi/6.0)" />



    <!-- 最大張力・最低張力の設定 -->
    <motor_force id="-1" unit="N"  min="0.02" max="4.2"/>

    <!-- キャリブレーション時のPWMのデューティ比の設定 -->
    <motor_pwm   id="-1" unit="percent" calibDuty="20.0" afterCalibDuty="10.0" maxDuty="100.0"/>

    <!-- motor_pid_imp　リリース時は削除 -->
    <!-- インピーダンス制御時のPIDの係数設定 -->
    <!--<motor_pid_imp   id="-1" unit="relative" Kp="1.25" Ki="0.125" Kd="-0.25"/>-->
    <motor_pid_imp   id="-1" unit="relative" Kp="0.75" Ki="0.005" Kd="-0.25"/>

    <!-- motor_pid_adm　リリース時は削除 -->
    <!-- アドミッタンス制御時のPIDの係数設定 -->
    <motor_pid_adm   id="-1" unit="relative" Kp="-128.0" Ki="-0.1" Kd="0.0" add_count="10"/>

    <correction_targetForceOpen id="-1" isActive="true" unit="relative" a0="-5.11050353155624e-3" a1="3.26673957621326e-1" a2="-2.69719298245601e-1" a3="0"/>
    <correction_adc_to_force id="-1" isActive="true" unit="relative" a0="8.71383002961969e-3" a1="7.18510550255477e-2" a2="0" a3="0"/>

  </spidar_motor_definition>

  <!-- コントローラに接続されているモータの定義（idはコントローラ系モータ番号） -->
  <controller_motor_definition>
    <rotation_dir id="0" unit="direction" direction="b"/>
    <rotation_dir id="1" unit="direction" direction="b"/>
    
    <rotation_dir id="2" unit="direction" direction="b"/>
    <rotation_dir id="3" unit="direction" direction="b"/>
    <rotation_dir id="4" unit="direction" direction="b"/>
    
    <rotation_dir id="5" unit="direction" direction="b"/>
    <rotation_dir id="6" unit="direction" direction="a"/>
    <rotation_dir id="7" unit="direction" direction="b"/>

    <!--プーリの半径 [mm]-->
    <pully    id="-1" unit="mm" radius="5.0"/>

    <!--Maxon 271107(201940:MRエンコーダTypeM 512Imp) の相順(a or b)と分解能[パルス/回転]-->
    <encoder  id="-1" unit="pulsePerTurn" resolution="512" interpolation="false"/>

    <!--Maxon 271107(220429:RE-max24) のトルク定数 [mNm/A] と端子間抵抗 [ohm] と実際にモータにかけている端子間電圧[v]-->
    <dc_motor id="-1" unit="mNmPerA" torque_constant="21.3" unit_r="ohm" terminal_r="6.46*0.5" unit_v="v" terminal_v="12.0"/>

  </controller_motor_definition>


</spidar_ahs>
